// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AlzaSyAw4uc77U6d8tZZmGcKzs8EIMqTTUMXVgo',
    appId: '1:36096427877:web:your-web-app-id',
    messagingSenderId: '36096427877',
    projectId: 'illusion-note-app',
    authDomain: 'illusion-note-app.firebaseapp.com',
    storageBucket: 'illusion-note-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AlzaSyAw4uc77U6d8tZZmGcKzs8EIMqTTUMXVgo',
    appId: '1:36096427877:android:950de65ab1910081842754',
    messagingSenderId: '36096427877',
    projectId: 'illusion-note-app',
    storageBucket: 'illusion-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AlzaSyAw4uc77U6d8tZZmGcKzs8EIMqTTUMXVgo',
    appId: '1:36096427877:ios:your-ios-app-id',
    messagingSenderId: '36096427877',
    projectId: 'illusion-note-app',
    iosBundleId: 'com.mgjeong.illusion',
    storageBucket: 'illusion-note-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AlzaSyAw4uc77U6d8tZZmGcKzs8EIMqTTUMXVgo',
    appId: '1:36096427877:macos:your-macos-app-id',
    messagingSenderId: '36096427877',
    projectId: 'illusion-note-app',
    iosBundleId: 'com.mgjeong.illusion',
    storageBucket: 'illusion-note-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AlzaSyAw4uc77U6d8tZZmGcKzs8EIMqTTUMXVgo',
    appId: '1:36096427877:windows:your-windows-app-id',
    messagingSenderId: '36096427877',
    projectId: 'illusion-note-app',
    authDomain: 'illusion-note-app.firebaseapp.com',
    storageBucket: 'illusion-note-app.appspot.com',
  );
} 